### ISSUE TITLE
Game table skal ændres

### ISSUE THREAD

**Issue by DjGlatnakke** [Distribuerede-systemer/snake#21]
Game objektet er blevet udvidet med flere parametre. Vi skal derfor også have udvidet Game-table i databasen og have lavet en nyt sql-dump.
Kan du klare den dataguy?

**Comment by jannikf** [comment]
Hvad er 'newgame' og 'endgame' til?



--Please excuse typos and brevity

**Comment by DjGlatnakke** [comment]
Tror det skulle have været istedet for status. Jeg gik bare ud fra at klassen "Game" i develop branchen var den endelige version af game objektet så jeg fik metoderne til at virke med den. Ellers bare ret objektet til. Det er alligevel kun 2-3 metoder der skal rettes.

**Comment by NichlasH** [comment]
Hvor langt er du med Databasen Jannik?

**Comment by jannikf** [comment]
Hvis I lader mig være 'Dataguy the Database Dictator' så skal jeg nok lave den færdig i dag.



--Please excuse typos and brevity
