### ISSUE TITLE
SQL dump af database struktur

### ISSUE THREAD

**Issue by jesperbruunhansen** [Distribuerede-systemer/snake#22]
Er der nogen som har mulighed for at lægge et sql-dump op af tabelstrukturen for jeres database?
Den behøver ikke nødvendigvis at indeholde rækker.

**Comment by jannikf** [comment]
Omdoebt fra .sql til .txt
[DBCon.txt](https://github.com/Distribuerede-systemer/snake/files/19143/DBCon.txt)

**Comment by jesperbruunhansen** [comment]
Mega nice, tak! :+1:
